# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "composer"
    labels:
      - "php dependency"
    ignore:
      - dependency-name: "symfony/*"
        versions: ["6.x","7.x"]


  ########################################################################################################################
  #
  #   Tools dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/ecs"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "Tools - ecs "
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/phpstan"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "Tools - psalm "
    labels:
      - "tool dependency"

  - package-ecosystem: "composer"
    target-branch: "main"
    directory: "/tools/rector"
    versioning-strategy: "increase"
    open-pull-requests-limit: 1
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "Tools - rector "
    labels:
      - "tool dependency"


  ########################################################################################################################
  #
  #   Github Actions dependencies
  #
  ########################################################################################################################
  - package-ecosystem: "github-actions"
    target-branch: "main"
    directory: "/"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    assignees:
      - "zerai"
    commit-message:
      include: "scope"
      prefix: "github-actions"
    labels:
      - "GHA dependency"