twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '_jobposting/src/Adapter/Http/Web/Templates': 'jobposting'

    form_themes: ['bootstrap_5_layout.html.twig']

when@test:
    twig:
        strict_variables: true
