controllers:
    resource: ../../src/Controller/
    type: annotation

controllers_jobposting_context:
    resource: ../../_jobposting/src/Adapter/Http/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
