JobPosting\Application\Model\JobPost\JobPost:
  type: entity
  table: 'jobpost'
  repositoryClass: JobPosting\Adapter\Persistence\Doctrine\MySqlJobPostRepository
  id:
    id:
      type: uuid
      generator:
        strategy: NONE
  fields:
    title:
      column: title
      type: string
      nullable: false
    description:
      column: description
      type: text
      nullable: false
    publicationStart:
      column: publication_start
      type: date_immutable
      nullable: true
    publicationEnd:
      column: publication_end
      type: date_immutable
      nullable: true