name: CD/CI

on:
  push:

jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/ils-jb/.github/workflows/commit-stage.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"

  acceptance-stage-workflow:
    name: Acceptance Stage
    needs:
      - commit-stage-workflow
    uses: zerai/ils-jb/.github/workflows/acceptance-stage.yaml@main
    with:
      triggering-sha: "${{ github.sha }}"
