name: CD/CI

on:
  push:

jobs:
  commit-stage-workflow:
    name: Commit Stage
    uses: zerai/ils-jb/.github/workflows/commit-stage.yaml@main
    secrets: inherit
    with:
      triggering-sha: "${{ github.sha }}"
